use shadow;

set names utf8;

INSERT INTO parameters VALUES ('', '事项类型', '每个事项的类型');
INSERT INTO para_values VALUES ('', '1', '日常事务');
INSERT INTO para_values VALUES ('', '1', '生产问题');
INSERT INTO parameters VALUES ('', '事项优先级', '每个事项的优先级');
INSERT INTO para_values VALUES ('', '2', '最高级');
INSERT INTO para_values VALUES ('', '2', '较高级');
INSERT INTO para_values VALUES ('', '2', '正常');
INSERT INTO para_values VALUES ('', '2', '较低级');
INSERT INTO para_values VALUES ('', '2', '最低级');
INSERT INTO roles VALUES('', 'default');
INSERT INTO roles VALUES('', 'admin');
INSERT INTO roles VALUES('', 'common_1');
INSERT INTO roles VALUES('', 'common_2');
INSERT INTO roles VALUES('', 'manager');
INSERT into privileges VALUES ('', '系统管理');
INSERT into privileges VALUES ('', '日常事务');
INSERT INTO privileges values ('', '生产问题');
INSERT INTO role_priv VALUES('', '2', '1');
INSERT INTO role_priv VALUES('', '2', '2');
INSERT INTO role_priv VALUES('', '2', '3');
INSERT INTO role_priv VALUES('', '3', '2');
INSERT INTO role_priv VALUES('', '4', '3');
INSERT INTO role_priv VALUES('', '5', '2');
INSERT INTO role_priv VALUES('', '5', '3');
INSERT INTO users VALUES('', 'yiyd', sha1('123456'), '1', 'yiyd@qq.com');
INSERT INTO users VALUES('', 'yiyd1', sha1('123456'), '2', 'yiyd1@qq.com');
INSERT INTO users VALUES('', 'yiyd2', sha1('123456'), '3', 'yiyd2@qq.com');
INSERT INTO users VALUES('', 'yiyd3', sha1('123456'), '4', 'yiyd3@qq.com');
